# Generated by Django 5.2.13 on 2026-07-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("coach", models.CharField(max_length=255)),
                ("crest", models.ImageField(upload_to="teams/crests/")),
                ("is_active", models.BooleanField(default=True)),
                ("stadium", models.CharField(blank=True, max_length=255)),
                ("motto", models.CharField(blank=True, max_length=255)),
                ("fans_name", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
