# Generated by Django 5.2.13 on 2026-07-01 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
    ]
